settings:
  # Name of the service account within each namespace that should be used for tiller
  serviceAccount: "tiller"

namespaces:
  kube-system:
  stable:
    protected: false
    installTiller: true
    labels:
      env: "stable"

helmRepos:
  stable: "https://kubernetes-charts.storage.googleapis.com"
  incubator: "http://storage.googleapis.com/kubernetes-charts-incubator"
  holisticode: "https://raw.githubusercontent.com/holisticode/helm-charts-artifacts/master/"

apps:
  # Private cluster
  private-swarm:
    tillerNamespace: "stable"
    namespace: "stable"
    name: "swarm-private"
    enabled: true
    chart: "holisticode/swarm-private"
    version: "0.0.5"
    description: "(Private) Swarm cluster"
    valuesFiles:
      - "deployment/private-swarm.yaml"
      - "deployment/version.yaml"
    set:
      swarm.replicaCount: "$STABLE_PRIVATE_REPLICAS"
    wait: true
    timeout: 600
  private-smoke-a:
    tillerNamespace: "stable"
    namespace: "stable"
    name: "private-smoke-a"
    enabled: true
    chart: "holisticode/smoke"
    version: "0.0.2"
    description: "(Private) Smoke test: Upload and sync"
    valuesFiles:
      - "deployment/private-smoke-a.yaml"
      - "deployment/version.yaml"
    set:
      smoke.config.swarmReplicas: "$STABLE_PRIVATE_REPLICAS"
    wait: false
